version: '3.4'

services:
  dislinkt.profile.webapi:
    container_name: dislinktprofilewebapi
    hostname: dislinktprofilewebapi
    image: ${DOCKER_REGISTRY-}dislinktprofilewebapi
    build:
      context: .
      dockerfile: Dislinkt.Profile/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - JAEGER_SERVICE_NAME=hello_service
        - JAEGER_AGENT_HOST=jaeger
        - JAEGER_AGENT_PORT=6831     
        - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    ports:
        - 8082:80
        - 8084:443
    depends_on:
        prometheus:
            condition: service_healthy
        grafana:
            condition: service_healthy
  grafana:
    container_name: grafana_dislinktprofilewebapi
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    volumes:
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
        prometheus:
            condition: service_healthy
    healthcheck:
        test: wget -q --tries=1 -O- http://localhost:3000/
        interval: 3s
        timeout: 3s
        retries: 10
        start_period: 10s

  prometheus:
    image: prom/prometheus
    container_name: prometheus_dislinktprofilewebapi
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    healthcheck:
        test: wget -q --tries=1 -O- http://localhost:9090/
        interval: 3s
        timeout: 3s
        retries: 10
        start_period: 10s  
  jaeger: 
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
